tallarium/reverse_proxy_plug

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_buffer_test.exs, test/reverse_proxy_plug_stream_test.exs
fixes #8 
fixes #5 
Prior to this, buffered responses were incorrectly forwarded to the client with the upstream `Transfer-Encoding: chunked` header intact, which causes an encoding error in Chrome.
=> Correctly proxy response headers in buffer mode

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_stream_test.exs
This will allow for creating custom plugs using ReverseProxyPlug functionality
which have freedom to do wrap additional custom logic around the request and
response.
A better API would probably be something akin to `Plug.Router` with its
`:match` and `:dispatch` (would be `:request` and `:response` in our case). But
this PR should be a good first step.
=> request and response functions

lib/reverse_proxy_plug.ex
This will allow for using `request/2` multiple times. Because
`Plug.Conn.read_body/1` can only be used once, all calls to `request/2` after
the first resulted in a request with empty body.
=> pass body into request/2 explicitly

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_stream_test.exs
Following the recommendation in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host and resolving the issue #26.
=> `host` header now includes the port when is not the default for the scheme

test/reverse_proxy_plug_buffer_test.exs
It was
```
warning: the first 2 default arguments in get_buffer_responder/3 are never used
test/reverse_proxy_plug_buffer_test.exs:29
```
=> remove test warning

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
**Description**
Because Phoenix reads the `raw body` and does not cache it if you used `reverse_proxy_plug` for post request  `Plug.Conn.read_Body(conn)` return `""` because already bean consumed by Phoenix.
In this [issue](https://github.com/phoenixframework/phoenix/issues/459) are few suggestions and one extension of Plug to allow you to cache the `raw body` and use it from `assigns.conn[:raw_body]`. The change simply adds condition to use that option with reverse proxy.
=> Add raw body check to allow reverse proxy to work with Phoenix

lib/reverse_proxy_plug.ex
The host_header_from_url was throwing a function clause error when using a HTTPS port that is not 443. With this fix I am able to proxy port 4001->4002 (HTTPS->HTTP & HTTPS->HTTPS)
Config used for testing:
```elixir
forward("/", to: ReverseProxyPlug,
upstream: "https://localhost:4002",
response_mode: :buffer,
client_options: [hackney: [
{:ssl_options, [{:cacertfile, "priv/ssl/cacert.pem"}]}
]])
```
=> Fixed HTTPS proxy with non standard port

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
This is a nice high utility plug, thanks.
Ran into a silent failure when I had a typo in the :upstream opt, which is actually required (though because of the Plug interface from naming it seems like an opt or option).
This change causes initialization, probably at compile time, to fail if we're missing the :upstream opt.
=> fail when missing upstream keyword opt because it's required

README.md, lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
A modification of https://github.com/tallarium/reverse_proxy_plug/pull/88
=> Allow error_callback to be a mfa tuple

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
There's a bug when the path is just the root, "/"
If upstream is "https://upstream.com":
Current behavior is it will result in "https://upstream.com//"
This patch fixes things so the request will be to "https://upstream.com/"
=> don't add double slashes when it's the root path

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
As uncovered here: https://github.com/tallarium/reverse_proxy_plug/pull/88#issuecomment-734416095.
=> Fix error_callback as an MFA tuple

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
According to Plug.Conn docs body cannot be fetched multiple times,
so if we have a raw_body is reasonable that someone already fetched it.
In this case we *must* avoid reading it again, because it can stall the connection
since Plug adapter will wait until timeout for a never arriving additional body data.
Also docs explicitly states that if raw_body is present is always used,
so let's enforce such case.
=> When raw_body is provided always use it.

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
Hackney requires that cookies are specified as part of the hackney client options.
Resolves #125
=> Recycle cookies in upstream request

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
Also added a helper function for validating request headers.
Resolves #81
=> Handle x-forwarded-for headers

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
Transfer-Encoding header violates RFC 7230:
https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.1
> A server MUST NOT send a Transfer-Encoding header field in any response with a status code of 1xx (Informational) or 204 (No Content).
We are having trouble to update our service mesh, because the new version are dropping requests, that are not compliant with the HTTP spec.
And I think this PR also resolves this issue #36
=> Removes transfer-encoding header from responses with non compliant status codes

lib/reverse_proxy_plug/http_client/adapters/tesla.ex
query in tesla must be list but request query params can be map
=> normalize tesla env struct query

lib/reverse_proxy_plug.ex, test/http_client/adapters/httpoison_test.exs, test/reverse_proxy_plug_test.exs
When the `:response_mode` option is set to `stream` and we use `HTTPoison` with `hackney`, the `recv_timeout` which we set to `client_options` is not working as expected, the plug does not send a response, because it is not listening to `HTTPoison.Error` in `ReverseProxyPlug.stream_response/2`, this PR aims to fix this behavior.
=> fix: handle httpoison async errors when response mode is stream

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
In the use case we have using this library, we want to have the same behavior if we change the response_mode when adding upstream headers to the current conn, today this is not true.
When we use `response_mode: :stream` the code add headers with `Plug.Conn.put_resp_header/3` that replace the headers that already exists in the conn.
When we use `response_mode: :buffer` the code add headers with `Plug.Conn.prepend_resp_headers/2` that prepends the upstream headers in the conn resp headers.
This PR attempts to resolve this issue by adding a new option to change the header addition behavior according to response_mode. And set the default options to values that will be backwards compatible.
And I think this PR also helps to solve this issue …
=> feat: new option to change headers addition behavior

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
fixes #175 
with some caveats:
- this removes the behaviour where `{:stream, X}` was returned. It was not clear whether this ever worked with any other adapter than `HTTPoision` - https://github.com/tallarium/reverse_proxy_plug/issues/176 tracks the work here. But we are now storing in memory request bodies that may have previously been streamed.
- the `read_body` interface (the return value) changes, but this shouldn't be considered part of the public interface for the plug
=> rewrite read_body to carry conn forward

README.md, lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs, test/support/test_reuse.ex
fixes #150
since downcasing headers is not something that intermediate hops necessarily need to do.
`String.downcase`'ing again in `remove_hop_by_hop_headers` is strictly unnecessary, but it would be useful to have some separate header utility functions for common operations like this (and optimize it there)
=> Optional upstream transformation

lib/reverse_proxy_plug.ex, lib/reverse_proxy_plug/http_client.ex, lib/reverse_proxy_plug/http_client/adapters/httpoison.ex, test/reverse_proxy_plug_test.exs, test/support/test_reuse.ex
fixes #148 
and throw an error if the client adapter does not support the response mode configured.
=> refactor stream response handling to optional callback

mix.exs
not required by the library itself. `bypass` requires the library, but it is a test-only dependency
=> remove cowboy dependency

lib/reverse_proxy_plug.ex, test/reverse_proxy_plug_test.exs
fixes #193 
After 3476177d1d524abbac73af30c25c701d84d20eba, first released in 2.4.0, we now check for the existence of a function (`stream_response/1`) during module load.
The previous code would have always checked to ensure `HTTPoison` was loaded using `Code.ensure_loaded/1`.
Use `Code.ensure_loaded/1` to ensure that the module is loaded or raise an exception if it cannot be loaded, and rewrite `ensure_http_client` so that it happens in all cases.
(`Code.ensure_loaded!` was first available in 1.12. When the next major version is released, the current case statement will be cleaned up in favour of this)
=> ensure adapter module is loaded before proceeding

lib/reverse_proxy_plug.ex, lib/reverse_proxy_plug/http_client.ex, lib/reverse_proxy_plug/http_client/adapters/httpoison.ex, lib/reverse_proxy_plug/http_client/async_response.ex, test/http_client/adapters/httpoison_test.exs, test/reverse_proxy_plug_test.exs, test/support/test_reuse.ex
so we can support other adapters which require special options to be provided to the `request` function
=> refactor to separate interface for requests with streamed responses

lib/reverse_proxy_plug.ex, lib/reverse_proxy_plug/http_client/adapters/httpoison.ex
No need to have another set of defaults - using the adapter defaults is perhaps the least surprising
=> Remove default timeout options

lib/reverse_proxy_plug/http_client/adapters/req.ex
caught during testing `:buffer` response mode for `req` 0.3.x while investigating #226
=> Req adapter fixes

mix.exs
depend on particular minor releases of req pre-1.0, since the interface and behaviour changes
=> correct req dependency

lib/reverse_proxy_plug/http_client/adapters/req.ex, test/http_client/adapters/req_test.exs
see #241 for a description of the change, with a removal of the `.tool-versions` change
=> fix(req): do not merge set-cookie response headers
